version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"
    restart: unless-stopped

# networks:
#   mongo_network:
#     driver: bridge

# volumes:
#   mongodb_data:
#     driver: local